#!/bin/bash

case $BLOCK_BUTTON in
    1) $HOME/.spotify-i3/sp play ;; # left click
    4) $HOME/.spotify-i3/sp next ;; # scroll up
    5) $HOME/.spotify-i3/sp prev ;; # scroll down
esac

if $HOME/.spotify-i3/sp status | grep 'Paused' > /dev/null; then
    printf '\xef\x81\x8c ' # fa-pause
else
    printf '\xef\x81\x8b ' # fa-play
fi
$HOME/.spotify-i3/sp current-oneline